feat: update scripts to share more code, add flag to skip code gen and tests

diff --git a/scripts.yaml b/scripts.yaml
--- a/scripts.yaml
+++ b/scripts.yaml
@@ -163,22 +163,46 @@ test-suite:
     - (+) {$test-suite:revali_server}
     - (+) {$test-suite:revali_client}
 
+  _test: |
+    {$test-suite:_pubspec:comment-out}
+
+    if [ -z "{--skip-gen}" ]; then
+      dart run revali dev --generate-only --recompile
+    fi
+
+    {$test-suite:_pubspec:uncomment}
+
+    if [ ! $? = 0 ]; then
+      echo "failed to generate revali code"
+      exit 1
+    fi
+
+    if [ -n "{--gen-only}" ]; then
+      exit 0
+    fi
+
+    dart test
+
   _pubspec:
     comment-out: |
       # get the line number of the first line that contains 'path: .revali/*'
       LINE_NUMBER=$(grep -n "path: .revali/*" pubspec.yaml | cut -d: -f1)
 
-      # comment out the line and the preceding line
-      sed -i '' "$((LINE_NUMBER))s/^/#/" pubspec.yaml
-      sed -i '' "$((LINE_NUMBER - 1))s/^/#/" pubspec.yaml
+      if [ -n "$LINE_NUMBER" ]; then
+        # comment out the line and the preceding line
+        sed -i '' "$((LINE_NUMBER))s/^/#/" pubspec.yaml
+        sed -i '' "$((LINE_NUMBER - 1))s/^/#/" pubspec.yaml
+      fi
 
     uncomment: |
       # get the line number of the first line that contains 'path: .revali/*'
       LINE_NUMBER=$(grep -n "path: .revali/*" pubspec.yaml | cut -d: -f1)
 
-      # uncomment the line and the preceding line
-      sed -i '' "$((LINE_NUMBER))s/^#//" pubspec.yaml
-      sed -i '' "$((LINE_NUMBER - 1))s/^#//" pubspec.yaml
+      if [ -n "$LINE_NUMBER" ]; then
+        # uncomment the line and the preceding line
+        sed -i '' "$((LINE_NUMBER))s/^#//" pubspec.yaml
+        sed -i '' "$((LINE_NUMBER - 1))s/^#//" pubspec.yaml
+      fi
 
   revali_client:
     (aliases): client
@@ -190,21 +214,7 @@ test-suite:
       - (+) {$test-suite:revali_client:websocket}
     _package: |
       cd test_suite/constructs/revali_client/$DIR || exit 1
-
-      {$test-suite:_pubspec:comment-out}
-
-      if [ -z {--skip} ]; then
-        dart run revali dev --generate-only --recompile
-      fi
-
-      {$test-suite:_pubspec:uncomment}
-
-      if [ ! $? = 0 ]; then
-        echo "failed to generate revali code"
-        exit 1
-      fi
-
-      dart test
+      {$test-suite:_test}
 
     primitive-return-types: |
       DIR=primitive_return_types
@@ -245,17 +255,7 @@ test-suite:
       - (+) {$test-suite:revali_server:params}
     _package: |
       cd test_suite/constructs/revali_server/$DIR || exit 1
-
-      if [ -z {--skip} ]; then
-        dart run revali dev --generate-only --recompile
-      fi
-
-      if [ ! $? = 0 ]; then
-        echo "failed to generate revali code"
-        exit 1
-      fi
-
-      dart test
+      {$test-suite:_test}
     methods: |
       DIR=methods
       {$test-suite:revali_server:_package}
